version: '3.7'

services:
  podcasts:
    build:
      context: .
    volumes:
      - .:/home/app/code
    depends_on:
      - "db"
    command: django-admin runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DEBUG: '1'
      PORT: '8000'
      SENTRY_DSN: ''
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres'

  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
