version: '3'
services:
  podcasts:
    build:
      context: .
    volumes:
      - .:/home/app/code
    depends_on:
      - db
    command: ./bin/web
    ports:
      - "8061:8000"
    environment:
      DEBUG: '1'
      PORT: '8000'
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres'
      SECRET_KEY: 'please-dont-use-me-in-production'
  db:
    image: postgres:9.6
