version: 2

jobs:
  test:
    working_directory: ~/code
    environment:
      IMAGE_NAME: podcasts
      DJANGO_SETTINGS_MODULE: podcasts.settings
      PYTHONPATH: /home/circleci/code
    docker:
      - image: circleci/python:3.7-stretch
      - image: circleci/postgres:9.6.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    steps:
      - checkout
      - run:
          name: Install requirements
          command: sudo pip install -r requirements.txt
      - run:
          name: Run collectstatic
          command: django-admin collectstatic --no-input
      - run:
          name: Run linting
          command: flake8 .
      - run:
          name: Run black
          command: black --check .
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Run tests
          environment:
            DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/postgres'
          command: py.test -vv -s

workflows:
  version: 2
  build-master:
    jobs:
      - test
