version: 2

jobs:
  test:
    working_directory: ~/code
    environment:
      IMAGE_NAME: podcasts
      DJANGO_SETTINGS_MODULE: podcasts.settings
      PYTHONPATH: ~/code/src
    docker:
      - image: circleci/python:3.7-stretch
      - image: circleci/postgres:9.6.9
    steps:
      - checkout
      - run:
          name: Install requirements
          command: sudo pip install -r requirements.txt
      - run:
          name: Run linting
          command: flake8 .
      - run:
          name: Run black
          command: black --check .
      - run:
          name: Run tests
          command: py.test -vv -s

workflows:
  version: 2
  build-master:
    jobs:
      - test
